### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mahyariiii** [Afiniel-tech/Yiimpool-Installer#1]
daemon builder is not fix
Until the problem is resolved
I try to install coins directly on the root
![daemoonbuilder problem](https://user-images.githubusercontent.com/94556716/165104508-3c23918c-f57b-480f-b579-0504c4814f93.jpg)

**Comment by mahyariiii** [comment]
Does not work
Most parts have problems with the site template
Other sections of the coin settings are empty   - 
..................................................................................................................................................................



*********************************************************************************
![add coin blunk](https://user-images.githubusercontent.com/94556716/165107897-b7b16067-c4ee-46d0-b560-937cc9fa9d37.jpg)

**Comment by afiniel** [comment]
It's now fit and the yiimp is mineable but its still Hex #FFF on the main page, that will bee fixed soon. 
![bild](https://user-images.githubusercontent.com/44875524/165753620-c1b3d0f2-ab27-471e-88e6-383be7d04924.png)

**Comment by afiniel** [comment]
And the DaemonBuilder works again.

´But the fix is not live yet you can use the dev branch mean while: to install the dev branch use:

`curl https://raw.githubusercontent.com/Afiniel-tech/Yiimpool-Installer/dev-v1.0.3/bootstrap.sh | bash`

Main branch come with more fixes soon. Regards Afiniel, and please open issue again if you find another issue :)
