### ISSUE TITLE
The differences

### ISSUE THREAD

**Issue by mahyariiii** [Afiniel-tech/Yiimpool-Installer#2]
Hello
Please note the differences between your application and https://github.com/cryptopool-builders/Multi-Pool-Installer
And what has been upgraded or updated?

**Comment by afiniel** [comment]
## Hello Thank you for question.

Feel free to try install it can try it out. I currently more more on my Yiimp fork then the installer right now, because the installer it's fully working and don't need a patch atm. But Yiimp Stratum upgrade and nomp versions coming soon. I will try to add ass many pool portals/ protocols as i have time with. Hope you got your answer, if not feel free to open again!

### Regards afi
